### ISSUE TITLE
Remember state (on/off/mode) and position (of each window)

### ISSUE THREAD

**Issue by raptormama** [maxheyn/TorghastTeams#12]
Clean/simple mode allows the user to individually place each of the party members' power displays. Ideally, remembering state (is the addon displayed at all?) should be remembered.

If the addon was enabled at exit (whether at the end of level 6 or any other way) it should reenable itself, go back to the last-used state, and restore window positions (this last might have to go by index number in the party - 1, 2, 3, 4).

Maybe toggles for remembering position/state could be part of an eventual preference pane way in the future.

**Comment by maxheyn** [comment]
Working on this now, thanks!

**Comment by accuracy114** [comment]
Thanks for the suggestion again, we have added many new features in #13 

Now, the addon remembers the state (simple/default) and the position of the each frame. 
Left click the minimap button to show or hide the frames. Ctrl + left click the button to toggle between the two different modes.

Let us know if we have more questions!
