### ISSUE TITLE
Broker Support

### ISSUE THREAD

**Issue by ZehelFenris** [maxheyn/TorghastTeams#15]
I would like if i instead of a minimap button had the option to use a broker button instead as i try to keep my minimap clean and i have to many addons to remember all the slash commands

**Comment by maxheyn** [comment]
Hi, can you give an example of other addons that implement Broker Buttons so that we can take a look at them? We're not too familiar with them so pointing us to what you use for broker buttons will help us out.

**Comment by ZehelFenris** [comment]
two addons im using where either right click or left click opens them is
[Token Price Notifer](https://www.curseforge.com/wow/addons/simulationcraft)
[Simulationcraft](https://www.curseforge.com/wow/addons/simulationcraft)
its the same as if they was on minimap except you just add them on the broker addons and then click them there

**Comment by maxheyn** [comment]
Ah okay, gotcha. I'll look into that thanks!

**Comment by maxheyn** [comment]
Added in 52c401fbcf6a71a5606c643f5b78b4ae92f982e6, v1.1.2

Was a bit easier than I was expecting, thanks for bringing it up. 
Here's an example of what it looks like for me. 
![image](https://user-images.githubusercontent.com/16215993/103593147-04242900-4ec3-11eb-9a5a-8d8ddd32ee59.png)
Let me know if that's what you were expecting.

**Comment by raptormama** [comment]
![image](https://user-images.githubusercontent.com/5473082/103605701-3a20d780-4eda-11eb-867e-db498ac782b9.png)

Works perfectly in ElvUI!

**Comment by maxheyn** [comment]
@raptormama Haha I'll be honest I've been using ElvUI for a few months now and had no idea they had their own databroker bar.

**Comment by raptormama** [comment]
It's in the chat frames (and other places)! If you look at the screenshots I posted in my simple UI reports you can see DataBroker modules under the left and right chat frames, to the left and right of the zone at the top middle of the screen, and under the minimap at the top right. All of those can be customized. (The zone display up top is LocationPlus).

The image above is of the bottom of my left chat frame.

**Comment by maxheyn** [comment]
Oh wow just figured it out! Cool thanks! 😅
![image](https://user-images.githubusercontent.com/16215993/103610604-9130a780-4eee-11eb-8d48-dec6d3c4123f.png)
