### ISSUE TITLE
Unzip Hangs Cannot upgrade nor install v1.1.1 nor 1.1.2. via Curseforge. Unzip Hangs 33%

### ISSUE THREAD

**Issue by wuudogg** [maxheyn/TorghastTeams#16]
Cannot upgrade nor install v1.1.1 nor v1.1.2.zip via Curseforge. Unzipping Hangs at 33%

Can reproduce easily:
 Can install v1.0.0
 Can upgrade v1.0.0 to v1.1.0

 Cannot upgrade nor install beyond 1.1.0. to 1.1.1 nor 1.1.2 via Curse.
 Also deleted addon entirely and attempted fresh install 1.1.1 nor 1.1.2. Hangs at unzipping 33% for both versions.

Also see an "Error has occurred. Please check your connection and try again".

The older versions work fine

**Comment by maxheyn** [comment]
Looking at this now, thanks for the report.

**Comment by maxheyn** [comment]
Seems to be fixed in https://github.com/maxheyn/TorghastTeams/commit/ea94916ecdb19b4bdaecf90a15e611aac77ff9c8
Let me know if the issue still persists.
Thank you for the report!

**Comment by wuudogg** [comment]
Confirmed. The update to 1.1.3.zip was successful.  Thanks for the addon.

**Comment by maxheyn** [comment]
Thank you for the report, I would not have known otherwise! 😊
