### ISSUE TITLE
[BUG] Tooltips don't show for some powers

### ISSUE THREAD

**Issue by raptormama** [maxheyn/TorghastTeams#19]
For some powers that aren't a good fit for my class, effect doesn't show. Example follows (I am a shaman; ability shown is for a paladin).

![powerglitch](https://user-images.githubusercontent.com/5473082/104107373-419d0380-5281-11eb-930a-065f057b14ef.png)

Addon functionality doesn't seem to be affected other than the tooltip failing to display what the power does. I don't know whether it's an issue with the addon or whether the game is just failing to send the data.

**Comment by maxheyn** [comment]
Hi, unfortunately there's not much I can do about that. If it helps, any Anima Powers that display that line just mean that it's one of those that unlock a new talent for that class. If that other player were a Shaman, you'd be able to see what the power does if it was one that gave them new Shaman talents.

You can see here on WoWhead that it has the same issue: https://www.wowhead.com/spell=313840/highlords-gift
If you check the boxes for the various Paladin specs the tooltip changes, and if none are checked it will only display the same line as your image.
